services:
  stationeers:
    build:
      context: .
      target: runtime
      args:
        STEAMCMD_FORCE_PLATFORM: ${STEAMCMD_FORCE_PLATFORM:-}
        STATIONEERS_APP_ID: ${STATIONEERS_APP_ID:-600760}
        STATIONEERS_BRANCH: ${STATIONEERS_BRANCH:-public}
        STATIONEERS_BETAPASS: ${STATIONEERS_BETAPASS:-}
        STEAM_LOGIN: ${STEAM_LOGIN:-anonymous}
        STEAM_PASSWORD: ${STEAM_PASSWORD:-}
        STEAM_GUARD_CODE: ${STEAM_GUARD_CODE:-}
    container_name: stationeers
    restart: unless-stopped
    ports:
      - "${STATIONEERS_GAME_PORT}:27016/udp"
      - "${STATIONEERS_QUERY_PORT}:27015/udp"
    volumes:
      - ./data:/data
    command: >
      -nographics -batchmode
      ${STATIONEERS_ARGS}
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
